name: Lint and Format Check (Ubuntu Latest)

on: [push, pull_request]

permissions:
  contents: read

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

      - name: Install clang-format
        run: |
          sudo apt update && sudo apt install clang-format-15 -y
          sudo ln -sf /usr/bin/clang-format-15 /usr/bin/clang-format

      - name: Build with Lint and Format Check
        run: |
          cmake -B build && cmake --build build
        env:
          CXX: clang++-14
          LINT_AND_FORMAT_CHECK: true

      - uses: chartboost/ruff-action@v1
        name: Lint with Ruff
        with:
          version: 0.0.261
